# Generated by Django 3.1.3 on 2021-06-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagLine',
        ),
        migrations.AlterField(
            model_name='movie',
            name='backdrop',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
